### ISSUE TITLE
Add halotools, cachey?

### ISSUE THREAD

**Issue by rainwoodman** [bccp/conda-channel-bccp#2]

**Comment by nickhand** [comment]
I'm not sure how things like this work. If we include cachey here, I think we can install using

```
conda install -c bccp astropy --file requirements.txt
```

We might want to think about packaging ``cachey`` with `nbodykit` in the `extern` directory. Halotools isn't "bccp-affialiated" but I don't see that as an issue including it -- I think the bigger issue is maintaining another recipe when we don't need necessarily need to

**Comment by nickhand** [comment]
halotools we can grab from astropy channel and cachey has been added
