### ISSUE TITLE
Switch Corrfunc back to main repo instead of forked version

### ISSUE THREAD

**Issue by nickhand** [bccp/conda-channel-bccp#25]
The DD(s,mu) functionality has been merged into the master branch now and a new release tagged so we can safely build from the main repo instead of my forked version going forward.

**Comment by rainwoodman** [comment]
While you are on this, could you also take a look if the OSX conda packages work on your mac? (what version of xcode do you have?)

@cosmonomad reported that the binaries didn't work for him and I attempted a fix.

**Comment by nickhand** [comment]
Everything works fine on my mac, although I am up to date with the latest (OS X 10.13.2 and Xcode 9.2). So no issues for me with bccp/nbodykit#455
