### ISSUE TITLE
Automatically fetch the latest version from pypi.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/conda-channel-bccp#3]
This way we will omit the version numbers in requirements.yml.

Then we can have a cron job on nersc that triggers a rebuild every night via travis api.

https://docs.travis-ci.com/user/triggering-builds

**Comment by rainwoodman** [comment]
Closed by de183cc7ffa1b6960e65f8d55b93ff0baf3b6ba4.

**Comment by kbarbary** [comment]
If you missed it, travis has cron jobs itself now: https://docs.travis-ci.com/user/cron-jobs/
