### ISSUE TITLE
Update to include numpy 1.12.x

### ISSUE THREAD

**Issue by rainwoodman** [bccp/conda-channel-bccp#6]
Somehow it refuses to rebuild binaries for newer version of numpy.

**Comment by rainwoodman** [comment]
I think it is because mpsort was originally pinned to a numpy version; but then turned to not pinned to numpy. 

As a result, we have two builds of the same version of mpsort on anaconda pinned numpy and unpinned. 

conda automatically picks up the pinned version but the build machinary only builds the unpinned version.

I bumped the version of mpsort. I think this will resolve the issue.

**Comment by nickhand** [comment]
building for numpy versions 1.11.x, 1.12.x and 1.13x now
