### ISSUE TITLE
halotools

### ISSUE THREAD

**Issue by rainwoodman** [bccp/conda-channel-bccp#7]
halotools is not built on bccp, as a result, installing nbodykit from bccp by default only gives us 0.2.0. I propose we include halotools.
@nickhand

**Comment by nickhand** [comment]
Sounds good to me. Do you want to add it or I should I?

**Comment by nickhand** [comment]
Seems like the easiest installation is if we have all dependencies on bccp+defaults channels

**Comment by nickhand** [comment]
also @rainwoodman, I am confused why we only get 0.2.0. The astropy channel has the latest version 0.5.0, right?

**Comment by rainwoodman** [comment]
Please go ahead and add halotools! I mean nbodykit 0.2.0, not halotools 0.2.0

**Comment by nickhand** [comment]
halotools has been added now
